name = "flatten-do"
account_id = "b6641681fe423910342b9ffa1364c76d"
route = { pattern = "flatten.do.cf/*", zone_id = "610c7d50a0eb08ba67af06925613f507" }
main = "worker.js"
compatibility_date = "2022-08-23"
